# Generated by Django 4.1.2 on 2022-10-21 23:08

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=150)),
                ('release_year', models.IntegerField()),
                ('director', models.CharField(max_length=100)),
                ('movie_poster', models.ImageField(blank=True, upload_to='images/')),
                ('movie_plot', models.TextField()),
                ('movie_poster_url', models.URLField()),
                ('rating', models.FloatField(default=0.0, validators=[movies.models.validate_rating])),
            ],
        ),
    ]
